webshopProject/eshop/Pages/Basket.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using eshop.Persistence.Models;
using eshop.Helpers;
using Microsoft.AspNetCore.Identity;
using eshop.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;

namespace eshop.Pages
{
    public class BasketModel : PageModel
    {
        private readonly eshop.Persistence.Models.ESHOPContext _context;
        public OrderBasket Basket;
        public Decimal Total { get; set; }

        public BasketModel(eshop.Persistence.Models.ESHOPContext context)
        {
            _context = context;
            Basket = new OrderBasket();
        }


        public void OnGet()
        {
            Basket = SessionHelper.GetObjectFromJson<OrderBasket>(HttpContext.Session, "basket") ?? new OrderBasket();
            Total = Basket.BasketProduct.Select(bp => bp.Product.Price * bp.Quantity).Sum();
        }

        private void addProductToBasket(int productID)
        {
            var product = _context.Product.Find(productID);

            Basket = SessionHelper.GetObjectFromJson<OrderBasket>(HttpContext.Session, "basket") ?? new OrderBasket();

            BasketProduct basketProduct = new BasketProduct
            {
                Product = product
            };

            if (Basket.BasketProduct.Where(bp => bp.Product.Id == product.Id).Count() >= 1)
            {
                Basket.BasketProduct.Where(bp => bp.Product.Id == product.Id).First().Quantity += 1;
            }
            else
            {
                basketProduct.Quantity = 1;
                Basket.BasketProduct.Add(basketProduct);
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "basket", Basket);

        }
        public IActionResult OnPostAddToBasket(int productID, int quantity = 1)
        {
            addProductToBasket(productID);
            return RedirectToPage("Basket");
        }

        public IActionResult OnGetOrder()
        {
            Basket = SessionHelper.GetObjectFromJson<OrderBasket>(HttpContext.Session, "basket") ?? new OrderBasket();
            if(Basket.BasketProduct.Count() <= 0)
            {
                return Page();
            }
            return RedirectToPage("Order");
        }

        public IActionResult OnGetDelete(int productID)
        {
            Basket = SessionHelper.GetObjectFromJson<OrderBasket>(HttpContext.Session, "basket") ?? new OrderBasket();

            Basket.BasketProduct = Basket.BasketProduct.Where(bp => bp.Product.Id != productID).ToList();

            SessionHelper.SetObjectAsJson(HttpContext.Session, "basket", Basket);
            return RedirectToPage("Basket");
        }

        public IActionResult OnPostUpdate(int[] quantities)
        {
            Basket = SessionHelper.GetObjectFromJson<OrderBasket>(HttpContext.Session, "basket") ?? new OrderBasket();

            var basketEnum = Basket.BasketProduct.GetEnumerator();

            for (var i = 0; i < Basket.BasketProduct.Count(); i++)
            {
                basketEnum.MoveNext();
                basketEnum.Current.Quantity = quantities[i];
            }

            SessionHelper.SetObjectAsJson(HttpContext.Session, "basket", Basket);
            return RedirectToPage("Basket");
        }


    }
}

webshopProject/eshop/Pages/Catalogue.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using eshop.Persistence.Models;
using JW;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using eshop.Helpers;

namespace eshop.Pages.Catalogue
{
    public class Products : PageModel
    {
        private readonly eshop.Persistence.Models.ESHOPContext _context;

        public Pager Pager { get; set; }

        public SelectList PageSizeList { get; set; }
        public List<string> CategoryNameList { get; set; }
        public SelectList BrandNameList { get; set; }
        public int PageSize { get; set; }
        public string SelectedCategoryName { get; set; }
        public string BrandName { get; set; }
        public IEnumerable<CatalogueProductView> ProductsCatalogue { get;set; }

        public Products(eshop.Persistence.Models.ESHOPContext context)
        {
            _context = context;

            PageSizeList = new SelectList(new[] {10, 20, 50, 100, 200, 500, 1000 });
            PageSize = 10;

            List<string> tmpCategoryNameList = new List<string>() { "Any" };
            tmpCategoryNameList.AddRange(_context.Category.Select(c => c.Name).ToList());

            CategoryNameList = tmpCategoryNameList;

            BrandNameList = new SelectList(new[] { "" });

            ProductsCatalogue = new List<CatalogueProductView>();

            Pager = new Pager(0);
        }
        private void refreshSelectList()
        {
            List<String> tmpBrandNameList = new List<string>() { "Any" };

            if (SelectedCategoryName == "Any")
                tmpBrandNameList.AddRange(_context.Brand.Select(b => b.Name).ToList());
            else
                tmpBrandNameList.AddRange(_context.CatalogueProductView
                    .Where(cpv => cpv.Category == SelectedCategoryName)
                    .Select(cpv => cpv.BrandName)
                    .ToList());

            BrandNameList = new SelectList(tmpBrandNameList);
        }


        public async Task<IActionResult> OnGetAsync(int p = 1)
        {
            BrandName = SessionHelper.GetObjectFromJson<String>(HttpContext.Session, "BrandName") ?? "Any";
            SelectedCategoryName = SessionHelper.GetObjectFromJson<String>(HttpContext.Session, "SelectedCategoryName") ?? "Any";

            refreshSelectList();
	    
	    string sqlBrand = "CALL get_products_by_brand_name({0});";
	    string sqlCat = "CALL get_products_by_category({0});";

            if (SelectedCategoryName != "Any")
            {

                if (BrandName != "Any")
                {
                    ProductsCatalogue = await _context.CatalogueProductView.FromSqlRaw(sqlBrand, BrandName)
                        .ToListAsync();
                    ProductsCatalogue = ProductsCatalogue.Where(cp => cp.Category == SelectedCategoryName);
                }
                else
                {
                    ProductsCatalogue = await _context.CatalogueProductView.FromSqlRaw(sqlCat, SelectedCategoryName)
                        .ToListAsync();
                }
            }
            else {
                if (BrandName != "Any")
                {
                    ProductsCatalogue = await _context.CatalogueProductView.FromSqlRaw(sqlBrand, BrandName)
                        .ToListAsync();
                }
                else
                {
                    ProductsCatalogue = await _context.CatalogueProductView
                        .ToListAsync();
                }
            }

            var tmpPageSize = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "PageSize");
            if (tmpPageSize > 0)
                PageSize = tmpPageSize;

            if (ProductsCatalogue.Count() > 0)
            {
                Pager = new Pager(ProductsCatalogue.Count(), p, PageSize);
                if (ProductsCatalogue.Count() >= Pager.PageSize)
                {
                    ProductsCatalogue = ProductsCatalogue.Skip((Pager.CurrentPage - 1) * Pager.PageSize).Take(Pager.PageSize);
                }
            }
            else
                Pager = new Pager(0);

            return Page();
        }

        public void OnPostSelectedCategoryNameAsync(string categoryName)
        {
            SessionHelper.SetObjectAsJson(HttpContext.Session, "SelectedCategoryName", categoryName);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "BrandName", "Any");
        }

        public async Task<IActionResult> OnPostAsync(int pageSize, string brandName)
        {
            SessionHelper.SetObjectAsJson(HttpContext.Session, "PageSize", pageSize);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "BrandName", brandName);
            return (await OnGetAsync());
        }
    }
} 

webshopProject/eshop/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace eshop.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

webshopProject/eshop/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eshop.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

webshopProject/eshop/Pages/Order.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using eshop.Persistence.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using eshop.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace eshop.Pages
{
    public class OrderModel : PageModel
    {
        [BindProperty]
        public InputModel Input { get; set; }
        private readonly ESHOPContext _context;

        public OrderModel(ESHOPContext context)
        {
            _context = context;
            Input = new InputModel();
        }

        public class InputModel
        {

            [Required]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [Display(Name = "First Name")]
            public string FirstName { get; set; }

            [Required]
            [Display(Name = "Last Name")]
            public string LastName { get; set; }

            [Required]
            [Display(Name = "Delivery Address")]
            public string Address { get; set; }
        }

        public void OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                Input.Email = User.Identity.Name;
            }
            var userCustomerInfo = _context.Customer.Where(c => c.Email == User.Identity.Name);

            if (userCustomerInfo.Count() >= 1)
            {
                Input.FirstName = userCustomerInfo.First().FirstName;
                Input.LastName = userCustomerInfo.First().LastName;
                Input.Address = userCustomerInfo.First().Address;
            }
        }

        public async Task<IActionResult> OnPostSubmit()
        {
            var userCustomerInfo = _context.Customer.Where(c => c.Email == User.Identity.Name);
            var basket = SessionHelper.GetObjectFromJson<OrderBasket>(HttpContext.Session, "basket");

            if (Input.Email != null && 
                Input.FirstName != null && 
                Input.LastName != null && 
                Input.Address != null && 
                basket != null)
            {
                var order = new Order();

                if(userCustomerInfo.Count() == 0)
                {
                    Customer newCustomer = new Customer();
                    newCustomer.Email = Input.Email;
                    newCustomer.FirstName = Input.FirstName;
                    newCustomer.LastName = Input.LastName;
                    newCustomer.Address = Input.Address;

                    order.Customer = newCustomer;
                }
                else
                    order.Customer = userCustomerInfo.FirstOrDefault();

                order.IsPaid = true;
                order.Status = "Shipped";

                basket.OrderId = order.Id;
                order.DeliveryAddress = Input.Address;
                order.Date = DateTime.Now;

                _context.Order.Add(order);
                await _context.SaveChangesAsync();

                return Redirect("OrderRedirect/Success?orderID=" + order.Id);
            }

            return Redirect("OrderRedirect/Fail");
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            return Page();
        }
    }
}

webshopProject/eshop/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eshop.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

webshopProject/eshop/Pages/Basket.cshtml
@page
@model eshop.Pages.BasketModel
@{
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart</title>
</head>
<body>

    <h3>Basket</h3>
    <form method="post" asp-page="basket" asp-page-handler="Update">

        <table class="table table-sm table-striped table-bordered " border="1">
            <tr>
                <th>Action</th>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity <input type="submit" value="Update" /></th>
                <th>Sub Total</th>
            </tr>
            @foreach (var item in Model.Basket.BasketProduct)
            {
                <tr align="center">
                    <td align="center">
                        <a asp-page="basket" asp-page-handler="Delete" asp-route-productID="@item.Product.Id">Delete</a>
                    </td>
                    <td>@item.Product.Name</td>
                    <td>$@item.Product.Price</td>
                    <td><input type="number" name="quantities" value="@item.Quantity" min="1" style="width: 50px;" /></td>
                    <td>
                        $@(item.Product.Price * item.Quantity)
                    </td>
                </tr>
            }
            <tr>
                <td colspan="4" align="right">Total</td>
                <td align="center">$@Model.Total</td>
            </tr>
        </table>
    </form>

    @if(Model.Basket.BasketProduct.Count() >= 1){
        <a asp-page="basket" asp-page-handler="Order" class="orderButton">Make Order</a>
    }

</body>
</html>

webshopProject/eshop/Pages/Catalogue.cshtml
@page
@model eshop.Pages.Catalogue.Products
<!-- pager parameter controls -->
<
<section class="hero">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <span>Categories</span>
                    </div>
                    <ul>
                        @foreach (string Category in @Model.CategoryNameList)
                        {
                            <li><a href="" onclick="OnCategoryClick('@Category')">@Category</a></li>
                        }
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form action="#">
                            <input type="text" placeholder="What do yo u need?">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                </div>
                <div name="products_content">
                    <form method="post" class="container border text-left pt-2 mb-3">
                        <div class="form-row form-group">
                            <div class="col">
                                <label asp-for="PageSize">Items per page</label>
                                <select asp-for="PageSize" asp-items="Model.PageSizeList" class="form-control form-control-sm" onchange="this.form.submit()"></select>
                            </div>
                        </div>
                        <div class="form-row form-group">
                            <div class="col">
                                <label asp-for="BrandName">Brand</label>
                                <select asp-for="BrandName" asp-items=Model.BrandNameList class="form-control form-control-sm" onchange="this.form.submit()"></select>
                            </div>
                        </div>
                    </form>

                    <!-- items being paged -->
                    <table class="table table-sm table-striped table-bordered">
                        @foreach (var product in @Model.ProductsCatalogue)
                        {
                            <div class="product-element">
                                <tr>
                                    <td>@product.Name</td>
                                    <td>@product.BrandName</td>
                                    <td>@product.Price</td>
                                    <td>
                                        <a href="#" onclick="AddToBasket(@product.ProductID)">Add To Basket</a>
                                </tr>
                            </div>
                        }
                    </table>

                    <!-- pager -->
                    @if (Model.Pager.Pages.Any())
                    {
                        <nav class="table-responsive">
                            <ul class="pagination justify-content-center d-flex flex-wrap">
                                @if (Model.Pager.CurrentPage > 1)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="/">First</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="/?p=@(Model.Pager.CurrentPage - 1)">Previous</a>
                                    </li>
                                }

                                @foreach (var p in Model.Pager.Pages)
                                {
                                    <li class="page-item @(p == Model.Pager.CurrentPage ? "active" : "")">
                                        <a class="page-link" href="/Catalogue?p=@p">@p</a>
                                    </li>
                                }

                                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="/Catalogue?p=@(Model.Pager.CurrentPage + 1)">Next</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="/Catalogue?p=@(Model.Pager.TotalPages)">Last</a>
                                    </li>
                                }
                            </ul>
                        </nav>
                    }
                </div>

            </div>
        </div>
    </div>
</section>

@Html.AntiForgeryToken()
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
    function AddToBasket(productID) {
        $.ajax({
            type: 'POST',
            url: '/Basket?handler=AddToBasket',
            beforeSend: function (xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            data: { "productID": productID },
            success: function(){
                alert("Product added to basket");
            }
        });
    }

    function OnCategoryClick(category) {
        $.ajax({
            type: "POST",
            url: "?handler=SelectedCategoryName",
            beforeSend: function (xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            data: { "categoryName": category },
        });

    }

    $(".hero__categories").on('click', 'li', function (e) {
        $(this).parent().find('li.active').removeClass('active');
        $(this).addClass('active');

        var start = new Date().getTime();
        while (new Date().getTime() < start + 100);
    });
</script>

webshopProject/eshop/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Welcome to FLS Computers!</h1>
    <img src="~/img/flsBackground.png"/>
</div>

webshopProject/eshop/Pages/Order.cshtml
@page
@model eshop.Pages.OrderModel
@{
}


<div class="row">
    <div class="col-md-4">
        <form method="post" asp-page-handler="Submit">
            <h4>Order</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>

            @if (!User.Identity.IsAuthenticated)
            {
                <div class="form-group">
                    <label asp-for="Input.Email"></label>
                    <input asp-for="Input.Email" class="form-control" />
                </div>
            }
            <div class="form-group">
                <label asp-for="Input.FirstName"></label>
                <input asp-for="Input.FirstName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Input.LastName"></label>
                <input asp-for="Input.LastName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Input.Address"></label>
                <input asp-for="Input.Address" class="form-control" />
                <span asp-validation-for="Input.Address" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Make Order</button>
        </form>
    </div>
</div>